### ISSUE TITLE
Porting to Godot 3 : bugs to solve

### ISSUE THREAD

**Issue by StraToN** [godotengine/escoria#34]
I create this issue to gather help & efforts in porting Escoria to Godot 3.0. The main objective is to get Escoria's current test scene working on Godot 3.0, which is not the case out-of-the-box at the moment.

I am basing my issues on this branch: 
https://github.com/StraToN/escoria/tree/3.0

Issues to fix:
- [x] Escape menu does not open (described below)
- [x] mouse clicks have no effect on moving the player
- [x] Resource queue loader seems to hang
- [x] Missing `VisualServer.force_sync()` function in Godot 3.0 (simply needs to add `ClassDB::bind_method(D_METHOD("force_sync"), &VisualServer::sync);` in servers/visual_server.cpp:1447) --> easy to do, maybe create a PR
- [x] Remove `vm = get_tree().get_root().get_node("vm")` code lines in scripts. `global_vm.gd` is defined as singleton and can be called simply by its name. This can avoid multiple instances of `vm` being initialized.
- [x] HUD buttons not responding
- [x] Walking animations in disorder
- [x] Event queue not reset after action (eg: look at ice cream) causing input blocked
- [x] Make terrain's scale map work
- [x] Make terrain's light map work
- [x] Make inventory work (pickup object won't appear)
- [x] It seems I broke something: dialog when looking at ice cream won't appear (edit: fixed, apparently the interact_pos was unreachable)
- [x] Test Escoria in Daiza (https://github.com/flossmanualsfr/escoria) example game with Escoria 3.

Others:
- [x] ~Test the behaviour of Vector2.angle_to_point() as it needed to be tweaked. Verify it is not bugged in Godot, if yes create a bug report.~

**Comment by fleskesvor** [comment]
Nice. :smile: Do you want help with anything?

**Comment by StraToN** [comment]
@fleskesvor Eheh, sure I'd love some help. Well, just checkout that branch and try to run the test scene. 
Currently I see 2 big issues:
1/ Escape menu does not open (described above)
2/ mouse clicks have no effect on moving the player

**Comment by fleskesvor** [comment]
I will take a look at it tonight then, most likely.

Would this also be a good opportunity to clean the code base a little? There's a bunch of stuff that's commented out, and it might be more idiomatic of modern Godot to replace all the `vm = get_tree().get_root().get_node("vm")`s with an AutoLoad.

**Comment by StraToN** [comment]
Of course, cleaning the code base will be part of the job.
Regarding all `vm = get_tree().get_root().get_node("vm")` AFAIK it is the only (documented) way to get AutoLoaded scripts (`global_vm.gd` is already AutoLoaded in Project Settings).

**Comment by fleskesvor** [comment]
Ah, yes. I meant to mark it as a singleton/global (I don't remember what it's called in the project settings), so that it doesn't have to be assigned to a variable in every script where it's used.

**Comment by akien-mga** [comment]
>  Regarding all vm = get_tree().get_root().get_node("vm") AFAIK it is the only (documented) way to get AutoLoaded scripts (global_vm.gd is already AutoLoaded in Project Settings).

`get_node("/root/vm")` is a bit more elegant, or if you declare the autoload as Singleton, you can just call it by name: `vm`. Keep in mind that Escora was designed in the days of Godot 1.0 (or maybe even earlier), there's a ton of later engine improvements that punto never really got familiar with :)

**Comment by akien-mga** [comment]
I would also suggest to do code cleanups either before or after porting to 3.0, but not during, as it can introduce regressions which will be hard to identify. Of course removing some dead code is fine, but big refactorings should be in their own commits.

**Comment by StraToN** [comment]
> > Regarding all vm = get_tree().get_root().get_node("vm") AFAIK it is the only (documented) way to get AutoLoaded scripts (global_vm.gd is already AutoLoaded in Project Settings).

> 
> get_node("/root/vm") is a bit more elegant, or if you declare the autoload as Singleton, you can just call it by name: vm. Keep in mind that Escora was designed in the days of Godot 1.0 (or maybe even earlier), there's a ton of later engine improvements that punto never really got familiar with :)

Ah, indeed I didn't test this. We could indeed remove good portions of useless lines.

**Comment by fleskesvor** [comment]
>  if you declare the autoload as Singleton, you can just call it by name: `vm`.

Yes, this is what I was thinking of.

I agree that it's probably best to hold off on code cleanups until the project has been ported to 3.0.

**Comment by StraToN** [comment]
Alright, I just pushed some updates: test scene now reacts to mouse clicks, the player moves around 👍

**Comment by StraToN** [comment]
More fixes.
Also, I set the 2 autoload singletons to game.tscn and global_vm.tscn instead of their scripts. This causes HUD's buttons to not respond.

**Comment by fleskesvor** [comment]
Great work. :slightly_smiling_face: Unfortunately, I still can't even get the test scene to load, so I'm afraid I won't be of much help at this stage.

**Comment by StraToN** [comment]
@fleskesvor Can you submit an issue with more details so I can have a look ? I have no problem loading my branch :s

**Comment by StraToN** [comment]
Note for myself: Concerning event stack queue not being reset : I remarked that the element inserted in it was added an attribute "waiting": true which is never removed for an unknown reason.

**Comment by fleskesvor** [comment]
@StraToN Sorry for the late response. It actually works for me now with the latest 64 bit Linux build from http://godot3builds.digitecnology.com/. I tried pre-built binaries in addition to compiling it myself the last time, so I'm not sure why it's suddenly working, but yay! :smile:

**Comment by fleskesvor** [comment]
Regarding the event stack queue not being reset: I noticed that in `player.gd` a function is connected to the "animation_finished" signal, which causes the `anim_finished()` function to get called repeatedly:

```if has_node("animation"):
		get_node("animation").connect("animation_finished", self, "anim_finished")```

In `anim_finished()` an idle animation is played, which again triggers the same signal, and so on.

Maybe it's related?

**Comment by StraToN** [comment]
Hey @fleskesvor 
Thank you for testing out ^^. The problem with the stack queue was different: I was using the wrong function to set the mouse_ignore property in telon.gd:12 which doesn't exist anymore in 3.0. This is fixed now ;)
However, I did observe the problem you relate and it's definitely worth fixing it. Thanks!

**Comment by fleskesvor** [comment]
Yeah, I noticed that as well, so I changed the method signature to contain an optional parameter, and saw that it was being called with the name of the last animation to be played. Maybe that's a new feature of Godot 3?

Do you have any more details on the last remaining issue on the list, "Walking animations in disorder", or other features that haven't been ported over yet? I noticed that the light map and scale... map, thing(?) haven't been ported over yet. And possibly other things as well?

**Comment by StraToN** [comment]
@fleskesvor Yeah, I just fixed it. It was caused by `Vector2.angle_to_point()` function that doesn't seem to behave the same as 2.1's.

**Comment by StraToN** [comment]
Alright, I have the default demo scene working all correctly now.
I'll need some testing with other demos, such as (Escoria in Daiza)[https://github.com/flossmanualsfr/escoria]. Will do tonight if nobody can test this afternoon.

**Comment by fleskesvor** [comment]
I took a stab at getting Escoria in Daïza to work with your branch, but it was only moderately successful:

https://github.com/fleskesvor/escoria-in-daiza/tree/3.0

I started by trying to pull and merge all changes on the main repo, then I tried to convert it to Godot 3.0, because I figured that should make it easy to pull in the changes on your branch. The export just failed to complete though, so I instead copied the globals/ directory from your branch, and attempted to resolve issues manually. That sort of worked, and it's at least possible to start the test scene, but there's a ton of issues, since I haven't really figured out what needs changing yet.

I'm also just using your project file so far.

**Comment by StraToN** [comment]
@fleskesvor Thanks a lot for your testings. I experienced the same "export to 3.0" failure in Godot 2.1.

> EDIT 2: Looks like it's the SamplePlayer in the bamboo scenes that is preventing me from opening them in Godot 3. Deleting them from the bamboo scenes in Godot 2 enables me to at least load the scenes in Godot 3.
I ended up to this point as well yesterday evening before I had to stop for the night. That is not so surprising, as the whole sound system was rewritten from scratch in Godot 3.0. Since demo scene is too simple, I didn't have this problem while porting Escora to 3.0. 

I guess we'll have to change the SamplePlayers for the according replacing node in all scenes, and then make sure Escoria 3.0 is able to manage them.

**Comment by fleskesvor** [comment]
Ah, that makes sense then. Yeah, that's probably the best course of action then, and it should probably not take too much time either.

Could the reason why this wasn't an issue in Escoria be that there's no audio attached to the tree? I don't remember ever hearing any sound in the demo, so if there are scenes with sound, they might not be attached, and thus not causing any issues.

**Comment by StraToN** [comment]
> Ah, that makes sense then. Yeah, that's probably the best course of action then, and it should probably not take too much time either.

Indeed. I started this morning. My biggest worries are mostly related to HUD scenes, but that should be ok. I'll continue during midday break.

> Could the reason why this wasn't an issue in Escoria be that there's no audio attached to the tree? I don't remember ever hearing any sound in the demo, so if there are scenes with sound, they might not be attached, and thus not causing any issues.

There is actually one sound that should be played in the demo (a dog splash sound) when looking at the ice cream item. However, this sound file was never included in the repo (and I always forget to include it if I can find it). 
https://github.com/godotengine/escoria/blob/master/device/scenes/test/ice_cream.esc#L12
That's something to fix - of course, until we finally provide some really better example scene(s collection?).

**Comment by fleskesvor** [comment]
I have the hud scenes working (I think) on my branch, so you can probably just copy those. There might be some redundant stuff there that needs to be removed though.

Yeah, when everything's ported and works as before, it would be great to do some code cleaning, as well as adding some extra demo content that better shows off the features of the framework.

**Comment by StraToN** [comment]
@fleskesvor I just cloned your 3.0 branch, but it seems you didn't push your recent changes as good_bamboo.tscn and bad_bamboo.tscn won't open.

**Comment by fleskesvor** [comment]
Yeah, I was looking to get some input on that before I pushed. That can be fixed by removing those nodes in Godot 2 though.

**Comment by StraToN** [comment]
Ok, I thought you had already pushed that. Well, apart from this problems, all HUD scenes are broken: links to images resources don't work, positions are incorrect and most nodes that were linked with scripts are not anymore. Looks like it's going to ask more work than expected - but not because of Escoria porting work.

**Comment by fleskesvor** [comment]
Isn't the test scene running with the verb menu and inventory basket at the bottom in my last pushed commit? I'll take a proper look and see if there's stuff that I have working locally that I didn't push yet tonight.

Yeah, there's definitely a bunch of stuff left that needs some tweaking in this project in particular, even with Escoria working properly.

**Comment by fleskesvor** [comment]
I just pushed my commits with the SamplePlayers removed, so that it's possible to at least load the intro and second scene. As you noted though, everything's in the wrong place. There's probably lots of broken functionality as well.

**Comment by StraToN** [comment]
@fleskesvor I suggest you create an issue on your branch to keep track of such modified scenes

**Comment by fleskesvor** [comment]
@StraToN Good idea. I have done so here: https://github.com/fleskesvor/escoria-in-daiza/issues/1

I also just noticed that all attached scripts had disappeared from the demo scenes when porting them from Godot 2, and the text isn't being displayed on the labels in the menu.

**Comment by fleskesvor** [comment]
I attached the scripts to the demo scenes, and it's possible to walk around now. None of the dialogue stuff is working though and positioning is all wrong.

**Comment by fleskesvor** [comment]
I spent some time re-arranging the demo scenes while looking at the way they were originally set up in Godot 2. It's not perfect yet, and definitely not very playable, but it looks much better.

I also put some effort into fixing up the main menu and confirm quit dialogue to make sure it's possible to load and quit the game. There's some issue with loading the first scene from the menu, however, so it just fades in and then fades right back out again to a black screen.

I've also added the background music back in, added the pick up sounds and fixed the animations to work with the new nodes.

**Comment by fleskesvor** [comment]
I've fixed some more stuff to make the demo more playable. There are still several issues remaining though:

1. The intro scene starts but just fades to black when pressing the new game button from the main menu.
2. Text isn't properly aligned within buttons in the main menu.
3. Placeholder keys are not being translated (I think this might be a configuration setting)
4. Tooltips have the wrong font
5. Branching dialogue isn't displayed and halts the game
6. Player character isn't scaled correctly in the second scene

Not sure what's going on with # 5, but https://github.com/StraToN/escoria/blob/3.0/globals/global_vm.gd#L259 is supposed to trigger https://github.com/StraToN/escoria/blob/3.0/globals/dialog_dialog.gd#L32 but the signal is emitted but never intercepted.

Regarding # 6, there seems to be something interfering with manual setting of the scale property in `player.gd`, as the setter gets triggered immediately after trying to manually set the scale, and removing the scripts, makes it possible to change it.

**Comment by StraToN** [comment]
I add the translations and also added the scales and lightmap in scene 2.
My branch is forked from yours : https://github.com/StraToN/escoria-in-daiza

**Comment by fleskesvor** [comment]
Nice work. :+1: This certainly is a big improvement.

> Nope, the scale image was simply missing in the terrain node, and near/far values were wrong. I added the scales and lightmap and it all shows good.

This seems to actually fix another issue too, that I forgot to mention yesterday, in which frequently this line would throw a null pointer exception (or something similar):

https://github.com/fleskesvor/escoria-in-daiza/blob/3.0/device/globals/player.gd#L226

**Comment by StraToN** [comment]
@fleskesvor 
Concerning point 5, look at res://ui/dialog_default.tscn : it's all empty although textures seem set. They are actually set to wrong paths like `res://.import/avatar_old_man.png-2db224e5e9b43466a6dbb167ff5843d2.stex` .

**Comment by StraToN** [comment]
@fleskesvor Il fixed all your points.
I still see a problem: the bamboo god in scene 2 doesn't appear when it is triggered via dialogs.

**Comment by fleskesvor** [comment]
The issue with the bamboo god was that the opacity was overridden in the second scene, so the animation had no effect. There was also an issue with the angry animation. I've fixed both issues and have also pulled your fixes into my branch.

**Comment by StraToN** [comment]
Great job !
I just added one more small fix: font size of credits' button was not correct. You can pull the change from my branch.

I ran the game on Godot 2.1 and remarked that speech is normally played by the old panda in scene 1. This should be the last fix we have to do before we're done ;)

**Comment by fleskesvor** [comment]
I adjusted the position of the dialogue option prompt, so it appears as in the Godot 2 version now. I also added the lightmap back into the test scene.

**Comment by fleskesvor** [comment]
I think the problem is that the .spx format isn't supported anymore. The audio nodes don't recognize the speech files at all when trying to load them from the editor. I changed the format to .ogg and made changes accordingly in the project settings, and it works.

For reference, the command I used was:

`find -type f -name "*.spx" -exec sh -c 'ffmpeg -i "$0" -acodec libvorbis "${0%.spx}.ogg"' {} \;`

I'm not familiar enough with ffmpeg to tell if there are possible optimizations/quality improvements, but I don't know if it matters for this use case anyway.

There was also a bug in changing the volume in `globals/dialog_instance.gd` that should be added to your 3.0 branch.

**Comment by fleskesvor** [comment]
There's something strange going on with `globals/bg_music.gd` too, I think It seems like `set_state()` is being called before this assignment happens:

https://github.com/StraToN/escoria/blob/3.0/globals/bg_music.gd#L3

which means the function returns on line 19, so it never complains about the errors on lines 28 and 30.

**Comment by StraToN** [comment]
> EDIT 2: I don't know the first thing about audio, but this page from the docs plus things I'm reading on the internet seem to suggest that .ogg is best suited for longer audio clips and music, while wav is better for short sound effects, which seems to be the opposite of how they're used in this project? It probably doesn't matter though.

That is true indeed, but I don't think it matters for this demo project. The reason is that the decompression time required to play .ogg files is not worth the gain of disk space since the file is small. No big deal, this is true for other engines too so users won't do the bad choice :) .

We may as well delete .spx files as they are not useful no more anyway.

> There's something strange going on with globals/bg_music.gd too, I think. It seems like set_state() is being called before this assignment happens:
>
>https://github.com/StraToN/escoria/blob/3.0/globals/bg_music.gd#L3
>
>which means the function returns on line 19, so it never complains about the errors on lines 28 and 30.

That's odd. I remember I added the `onready` keyword myself somewhere. Maybe that was in this file? I'll test it myself to see if I detect anything.

**Comment by fleskesvor** [comment]
I don't think the issue is with the `onready` keyword, as assigning it in the `_ready()` function, like it used to be, has the exact same effect. It seems more like that the contract that the variable will truly be initialized when the scene is ready is broken, so maybe a bug in Godot 3? Checking for null and initializing the variable in the `set_state()` function works, but that seems like a band-aid solution if there's indeed a more fundamental problem.

**Comment by StraToN** [comment]
I wonder if this is related to the fact that `bg_music.tscn`'s script inherits `item.gd`. 
This causes this scene to be registered by the VM, and besides it causes the presence of an item in top-left corner of the game zone.
(`telon.tscn` has the same problem)

**Comment by fleskesvor** [comment]
Yeah, that sounds plausible. The behavior is the exact same in the original Godot 2 version anyway, so this is not a regression. Does it cause any issues besides the fact that it's currently not possible to start background music from an .esc script? It's worth investigating, but maybe there should be an issue for it, since the problem is already present.

**Comment by StraToN** [comment]
Alright, creating issue now. I think we can also consider this issue as resolved. May I ask you to create PR for Daiza 3.0 ? I'll create the PR for Escoria in the afternoon.

Concerning this point:
>Test the behaviour of Vector2.angle_to_point() as it needed to be tweaked. Verify it is not bugged in Godot, if yes create a bug report.

I think this behaviour is part of the broken stuff between 2.1 and 3.0. Let's forget it for now and wait for other users to point this out.

**Comment by fleskesvor** [comment]
Yes, I can do that. Should the current master branches be put in legacy 2.x branches for users who might not have started with Godot 3 yet?

**Comment by StraToN** [comment]
> EDIT 2: Come to think of it, I don't see the need to support Godot 2 users with new updates on a legacy branch, so that's probably redundant.

2 solutions : 
- either the current state of master will be tagged to 2.1 and 3.0 pulled over
- either the current state is put in a 2.1 branch that will be frozen, and 3.0 pulled over master

**Comment by akien-mga** [comment]
Do like Godot™, branch off to 2.1 and make master compatible with Godot's master branch. Once Godot 3.0 is released, branch off to 3.0 and sync stable stuff from master there every now and then.

**Comment by fleskesvor** [comment]
That sounds like a good idea. 🙂
I squashed things as much as I was able to and made a PR on Daïza. For some reason, trying to squash flossmanualsfr/escoria@2df4ed532605b2b4686449a7b3fe55bdf8f54a70 really messed up my graph, so I left it in place.

**Comment by StraToN** [comment]
@akien-mga Ok then we just have to branch off current master to a new 2.1 branch, and after that, force push our 3.0 work over master.

**Comment by StraToN** [comment]
Done! master branch is now compatible with Godot master. Escora 2.1 branch is compatible with Godot 2.1. Closing issue :)
